-- Creación de la base de datos para el Foro Turístico (Compatible con Supabase/PostgreSQL)

-- 1. Crear tipos ENUM personalizados si no existen
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('admin', 'seller', 'user');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
        CREATE TYPE user_status AS ENUM ('pending', 'approved', 'rejected');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'complaint_status') THEN
        CREATE TYPE complaint_status AS ENUM ('pending', 'answered');
    END IF;
END$$;

-- 2. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) DEFAULT NULL,
  role user_role NOT NULL DEFAULT 'user',
  status user_status NOT NULL DEFAULT 'approved',
  rejection_reason TEXT DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  country VARCHAR(100) DEFAULT NULL,
  company_name VARCHAR(200) DEFAULT NULL,
  google_id VARCHAR(255) DEFAULT NULL
);

-- 3. Tabla de Reservas
CREATE TABLE IF NOT EXISTS bookings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  tour_id VARCHAR(50) NOT NULL, -- Almacena el ID del tour en MongoDB
  tour_title VARCHAR(200) NOT NULL,
  date DATE NOT NULL,
  spots INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. Tabla de Quejas y Sugerencias
CREATE TABLE IF NOT EXISTS complaints (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  subject VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  reply TEXT DEFAULT NULL,
  status complaint_status NOT NULL DEFAULT 'pending',
  replied_by VARCHAR(100) DEFAULT NULL,
  tour_id VARCHAR(50) DEFAULT NULL,
  tour_title VARCHAR(200) DEFAULT NULL,
  seller_id INT DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_complaints_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 5. Insertar datos de respaldo
-- Datos para 'users'
INSERT INTO users (id, name, email, password, role, status, rejection_reason, created_at, country, company_name, google_id)
VALUES 
  (1, 'Administrador Foro', 'admin@foro.com', '$2a$10$.l1cISEkMmObeNt3DcVUduqCEqfRLQo9iG9jVwzWckm5DPFCIBmN.', 'admin', 'approved', NULL, '2026-07-08 01:00:21+00', NULL, NULL, NULL),
  (2, 'Julian Guzmán', 'julianguzman2900@gmail.com', '$2a$10$48C3r6QBVbIktPkQhnGNduHyKjlmYX0laNg5vtZEugyBJl5OfvBGm', 'seller', 'approved', NULL, '2026-07-08 01:19:59+00', NULL, NULL, '115788150456360143068'),
  (3, 'Jenifer Guzman', 'jl6634503@gmail.com', '$2a$10$RgI5mMZoWgcziCwuXfcXXuqGC2NtD/WN/XHDLWAek9YwwZXo66zce', 'user', 'approved', NULL, '2026-07-08 02:31:19+00', NULL, NULL, NULL),
  (4, 'jose guzman', 'jg3238503@gmail.com', NULL, 'user', 'approved', NULL, '2026-07-08 05:23:08+00', NULL, NULL, '111182066423036367169')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  password = EXCLUDED.password,
  role = EXCLUDED.role,
  status = EXCLUDED.status,
  rejection_reason = EXCLUDED.rejection_reason,
  created_at = EXCLUDED.created_at,
  country = EXCLUDED.country,
  company_name = EXCLUDED.company_name,
  google_id = EXCLUDED.google_id;

-- Ajustar secuencia del id de users
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE(MAX(id), 1)) FROM users;

-- Datos para 'bookings'
INSERT INTO bookings (id, user_id, tour_id, tour_title, date, spots, created_at)
VALUES 
  (1, 3, '6a4db6016592cff98803c708', 'Ruta al Volcán Acatenango', '2026-07-10', 5, '2026-07-08 02:35:10+00'),
  (2, 3, '6a4df701bd7eeca83bc8a8cd', 'fgfggdfgf', '2026-07-16', 3, '2026-07-08 08:16:01+00')
ON CONFLICT (id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  tour_id = EXCLUDED.tour_id,
  tour_title = EXCLUDED.tour_title,
  date = EXCLUDED.date,
  spots = EXCLUDED.spots,
  created_at = EXCLUDED.created_at;

-- Ajustar secuencia del id de bookings
SELECT setval(pg_get_serial_sequence('bookings', 'id'), COALESCE(MAX(id), 1)) FROM bookings;
